services:
  _defaults:
    autowire: true
    autoconfigure: true


  BoogieBaeren\ContaoGoogleSsoBundle\Controller\:
    resource: '../../Controller'

  BoogieBaeren\ContaoGoogleSsoBundle\Controller\LoginController:
    arguments:
      $userProvider: '@contao.security.backend_user_provider'

  google.sso:
    alias: Google\Client
    class: Google\Client
    arguments:
      $config:
        client_id: '%env(GOOGLE_SSO_CLIENTID)%'
        client_secret: '%env(GOOGLE_SSO_CLIENTSECRET)%'
  Google\Client: '@google.sso'
  #BoogieBaeren\ContaoGoogleSsoBundle\EventListener\:
  #  resource: '../../EventListener'

  #BoogieBaeren\ContaoGoogleSsoBundle\Service\:
  #  resource: '../../Service'
